### ISSUE TITLE
Can't install pocketVox correctly

### ISSUE THREAD

**Issue by cdmcruises** [benoitfragit/pocketVox#4]
Following http://forum.ubuntu-fr.org/viewtopic.php?pid=18604461#p18604461 that tutorial.
Added some modifications.
```bash
cd ../cmuclmtk-0.7
./autogen.sh
make
sudo make install
```
was for me
```bash
cd ../cmuclmtk-0.7
./configure
make
sudo make install
```
Because autogen.sh doesn't exist here.
And
```bash
wget -O french3g62K.lm.dmp.bz2 http://sourceforge.net/projects/cmusphinx/files/Acoustic%20and%20Language%20Models/French%20Language%20Model/french3g62K.lm.dmp.bz2/download
```
is now 
```bash
wget -O french3g62K.lm.dmp http://sourceforge.net/projects/cmusphinx/files/Acoustic%20and%20Language%20Models/French%20Language%20Model/french3g62K.lm.dmp/download
```
So the 2nd tar instruction on the forum is apparently not necessary.
French users will have a problem setup.sh in pocketsphinx, because of a non ASCII character. ("é" of "Téléchargements"). So I set UTF-8 encoding in the file. like that when the error appeared.
```bash
# -*- coding: utf8 -*-
```
But my real problem is here :
-
On  ~/Téléchargements/pocketVox-master$ make
I have this
```bash
  CC     pocketvox-controller.lo
pocketvox-controller.c: In function 'pocketvox_controller_on_request':
pocketvox-controller.c:180:5: error: implicit declaration of function 'g_get_num_processors' [-Werror=implicit-function-declaration]
cc1: all warnings being treated as errors
```
So I can't move forward.

PS : I'm working on Ubuntu 12.04.

**Comment by benoitfragit** [comment]
Thank you for reporting that. Yhe last error is caused by Glib try to update it

**Comment by cdmcruises** [comment]
Okay I'm trying in fact to install it, have nothing found about glib on my computer. Je te tiens au courant.

**Comment by benoitfragit** [comment]
Je pense que tu n as pas une version de glib et/ou gtk assez recente

**Comment by cdmcruises** [comment]
Là manifestement le problème c'est gtk. Désolé mais je vais abandonner pour le moment, il y a un peu trop de dépendances à mon goût pour gtk, et comme j'y connais pas grand chose, je m'arrête avant de planter la bête. Le jour où je passerai à une version d'Ubuntu plus récente je testerai de nouveau. Bonne continuation !

**Comment by benoitfragit** [comment]
Que vrux tu faire ? Si tu veux la reconnaissance vocale en francais sans
pocketvox mais avec pocketdphinx c est pas dur je peux te dire comment te
creer un plugin gstreamer qui viendra se connecter au plugin pocksphinx

**Comment by cdmcruises** [comment]
Ok je veux bien, c'est ce que je cherche. A vrai dire, il y a 3 jours, j'ai eu envie de démarrer google2ubuntu, et en regardant un peu sur github parce que j'arrivais pas à le faire tourner, je suis arrivé ici :)
